apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL3JlZ2lzdHJ5LmdpdGxhYi5jb20iOnsidXNlcm5hbWUiOiJpbmZpbml0eWRvbiIsInBhc3N3b3JkIjoiUGd6b3pYZHlzRHNXQmF4SllBd1EiLCJlbWFpbCI6ImZ1dHVyZWRvbkBnbWFpbC5jb20iLCJhdXRoIjoiYVc1bWFXNXBkSGxrYjI0NlVHZDZiM3BZWkhselJITlhRbUY0U2xsQmQxRT0ifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: paws-pull-token
type: kubernetes.io/dockerconfigjson
