[package]
name = "paws"
version = "0.1.0"
authors = ["Austin Aigbe"]
edition = "2018"

[dependencies]
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11.3", features = ["json"] }
warp = "0.3.1"